file_type: csv
dataset_name: RefGenomeList
file_name: large_file
table_name: SourmashGather
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1 #allows for headers in rows
columns: 
  - intersect_bp
  - f_orig_query 
  - f_match
  - f_unique_to_query
  - f_unique_weighted
  - average_abund
  - median_abund
  - std_abund
  - name
  - filename
  - md5
  - f_match_orig
  - unique_intersect_bp
  - gather_result_rank
  - remaining_bp
  - query_filename
  - query_name
  - query_md5
  - query_bp
